# Generated by Django 3.1.1 on 2020-09-21 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to=ecommerce.models.get_catalog_path)),
            ],
            options={
                'db_table': 'catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.SmallIntegerField(default=0)),
                ('paid_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('payment_ref', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('favourite_color', models.ManyToManyField(to='ecommerce.Color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qty', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('catalog', models.ForeignKey(db_column='catalog', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.catalog')),
                ('order', models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.order')),
            ],
            options={
                'db_table': 'order_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='color',
            field=models.ForeignKey(db_column='color', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.color'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='size',
            field=models.ForeignKey(db_column='size', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.size'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(db_column='catalog', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.catalog')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': True,
                'unique_together': {('user', 'catalog')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='catalog',
            unique_together={('sku', 'size', 'color')},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('qty', models.IntegerField()),
                ('catalog', models.ForeignKey(db_column='catalog', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.catalog')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
                'unique_together': {('user', 'catalog')},
            },
        ),
    ]
